name: dailygrowth
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2
  dio: ^5.9.0
  fl_chart: ^0.65.0
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  sizer: ^2.0.15
  supabase_flutter: ^2.8.2
  image_picker: ^1.0.4
  record: ^6.0.0
  just_audio: ^0.9.36
  path_provider: ^2.1.4
  universal_html: ^2.2.4

  web: any
  flutter_local_notifications: any
  cron: any
  timezone: any
  # firebase_core: ^2.24.2
  # firebase_messaging: ^14.7.10
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/