#!/bin/bash

# Script pour nettoyer la base de données via l'interface Supabase
echo "🧹 Nettoyage de la base de données pour les tests..."

echo "Pour nettoyer complètement la base de données :"
echo ""
echo "1. Allez sur https://supabase.com/dashboard"
echo "2. Sélectionnez votre projet DailyGrowth"
echo "3. Allez dans 'SQL Editor'"
echo "4. Exécutez les commandes suivantes une par une :"
echo ""
echo "-- Supprimer les micro-défis utilisateurs"
echo "DELETE FROM user_micro_challenges;"
echo ""
echo "-- Supprimer les défis quotidiens"
echo "DELETE FROM daily_challenges;"
echo ""
echo "-- Supprimer les citations quotidiennes"
echo "DELETE FROM daily_quotes;"
echo ""
echo "-- Supprimer les profils utilisateurs"
echo "DELETE FROM user_profiles;"
echo ""
echo "5. Pour supprimer les comptes utilisateurs :"
echo "   - Allez dans 'Authentication' > 'Users'"
echo "   - Supprimez manuellement chaque utilisateur"
echo ""
echo "✅ Après cela, vous pourrez tester avec de nouveaux utilisateurs"
